eTickets/Controllers/ActorsController.cs
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;

namespace eTickets.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorService actorService;

        public ActorsController(IActorService actorService)
        {
            this.actorService = actorService;
        }

        public async Task<IActionResult> Index()
        {
            var actors = await actorService.GetAllAsync();
            return View(actors);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync([Bind("ProfilePictureUrl,FullName,Bio")]Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }

            await actorService.AddAsync(actor);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DetailsAsync(int id)
        {
            var actor = await actorService.GetByIdAsync(id);
            if (actor is null)
            {
                return View("NotFound");
            }

            return View(actor);
        }

        public async Task<IActionResult> EditAsync(int id)
        {
            var actor = await actorService.GetByIdAsync(id);
            if (actor is null)
            {
                return View("NotFound");
            }

            return View(actor);
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(int id, Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }

            await actorService.UpdateAsync(id, actor);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteAsync(int id)
        {
            var actor = await actorService.GetByIdAsync(id);
            if (actor is null)
            {
                return View("NotFound");
            }

            return View(actor);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmedAsync(int id)
        {
            await actorService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTickets/Controllers/CinemasController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
    public class CinemasController : Controller
    {
        private readonly ICinemaService cinemaService;

        public CinemasController(ICinemaService cinemaService)
        {
            this.cinemaService = cinemaService;
        }

        public async Task<IActionResult> Index()
        {
            var cinemas = await cinemaService.GetAllAsync();
            return View(cinemas);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync([Bind("Logo", "Name", "Description")]Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }

            await cinemaService.AddAsync(cinema);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DetailsAsync(int id)
        {
            var cinema = await cinemaService.GetByIdAsync(id);
            if (cinema is null)
            {
                return View("NotFound");
            }

            return View(cinema);
        }

        public async Task<IActionResult> EditAsync(int id)
        {
            var cinema = await cinemaService.GetByIdAsync(id);
            if (cinema is null)
            {
                return View("NotFound");
            }

            return View(cinema);
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(int id, Cinema cinema)
        {
            if (!ModelState.IsValid || id != cinema.Id)
            {
                return View(cinema);
            }

            await cinemaService.UpdateAsync(id, cinema);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteAsync(int id)
        {
            var cinema = await cinemaService.GetByIdAsync(id);
            if (cinema is null)
            {
                return View("NotFound");
            }

            return View(cinema);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmationAsync(int id)
        {
            var cinema = await cinemaService.GetByIdAsync(id);
            if (cinema is null)
            {
                return View("NotFound");
            }

            await cinemaService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTickets/Controllers/MoviesController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService movieService;

        public MoviesController(IMovieService movieService)
        {
            this.movieService = movieService;
        }

        public async Task<IActionResult> Index()
        {
            var movies = await movieService.GetAllAsync();
            return View(movies);
        }

        public async Task<IActionResult> SearchAsync(string searchString)
        {
            if (string.IsNullOrWhiteSpace(searchString))
            {
                return RedirectToAction(nameof(Index));
            }

            var allMovies = await movieService.GetAllAsync();
            var filteredResult = allMovies.Where(m => m.Name.Contains(searchString, StringComparison.CurrentCultureIgnoreCase) || m.Description.Contains(searchString, StringComparison.CurrentCultureIgnoreCase));
            return View(nameof(Index), filteredResult);
        }

        public async Task<IActionResult> DetailsAsync(int id)
        {
            var movie = await movieService.GetByIdAsync(id);
            if (movie is null)
            {
                return View("NotFound");
            }

            return View(movie);
        }

        public async Task<IActionResult> CreateAsync()
        {
            var movieDropdownsData = await movieService.GetMovieDropdownsAsync();

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.MovieCategories = new SelectList(movieDropdownsData.MovieCategories, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(MovieViewModel movie)
        {
            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await movieService.GetMovieDropdownsAsync();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.MovieCategories = new SelectList(movieDropdownsData.MovieCategories, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

                return View(movie);
            }

            await movieService.AddNewMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> EditAsync(int id)
        {
            var movie = await movieService.GetByIdAsync(id);
            if (movie is null)
            {
                return View("NotFound");
            }

            var response = new MovieViewModel
            {
                Id = movie.Id,
                Name = movie.Name,
                Description = movie.Description,
                Price = movie.Price,
                StartDate = movie.StartDate,
                EndDate = movie.EndDate,
                ImageUrl = movie.ImageUrl,
                MovieCategoryId = movie.MovieCategoryId,
                CinemaId = movie.CinemaId,
                ProducerId = movie.ProducerId,
                ActorIds = movie.ActorMovies.Select(m => m.ActorId).ToList()
            };

            var movieDropdownsData = await movieService.GetMovieDropdownsAsync();

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.MovieCategories = new SelectList(movieDropdownsData.MovieCategories, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(int id, MovieViewModel movie)
        {
            if (id != movie.Id)
            {
                return View("NotFound");
            }

            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await movieService.GetMovieDropdownsAsync();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.MovieCategories = new SelectList(movieDropdownsData.MovieCategories, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

                return View(movie);
            }

            await movieService.UpdateMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTickets/Controllers/OrdersController.cs
using eTickets.Data.Cart;
using eTickets.Data.Services;
using eTickets.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe.Checkout;
using System.Security.Claims;

namespace eTickets.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IMovieService movieService;
        private readonly ShoppingCart shoppingCart;
        private readonly IOrderService orderService;

        public OrdersController(IMovieService movieService, ShoppingCart shoppingCart, IOrderService orderService)
        {
            this.movieService = movieService;
            this.shoppingCart = shoppingCart;
            this.orderService = orderService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders = await orderService.GetUserOrdersByIdAndRoleAsync(userId, userRole);
            
            return View(orders);
        }
        public IActionResult ShoppingCart()
        {
            shoppingCart.ShoppingCartItems = shoppingCart.GetShoppingCartItems();
            var response = new ShoppingCartViewModel
            {
                ShoppingCart = shoppingCart,
                ShoppingCartTotal = shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddToCartFromHome(int id)
        {
            bool inCart = shoppingCart.GetShoppingCartItems().Exists(i => i.MovieId == id);
            if (!inCart)
            {
                var movie = await movieService.GetByIdAsync(id);
                if (movie != null)
                {
                    await shoppingCart.AddItemToCartAsync(movie);
                }
            }

            return RedirectToAction("Index", "Movies");
        }

        public async Task<IActionResult> AddItemToShoppingCartAsync(int id)
        {
            var movie = await movieService.GetByIdAsync(id);
            if (movie != null)
            {
                await shoppingCart.AddItemToCartAsync(movie);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCartAsync(int id)
        {
            var movie = await movieService.GetByIdAsync(id);
            if (movie != null)
            {
                await shoppingCart.RemoveItemFromCart(movie);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrderAsync()
        {
            var items = shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmail = User.FindFirstValue(ClaimTypes.Email);

            await orderService.StoreOrderAsync(items, userId, userEmail);

            // Payment using Stripe
            var domain = "https://localhost:7134";
            var options = new SessionCreateOptions
            {
                LineItems = new List<SessionLineItemOptions>(),
                PaymentMethodTypes = new List<string>
                {
                    "card"
                },
                Mode = "payment",
                SuccessUrl = domain + "/Orders/OrderConfirmation",
                CancelUrl = domain + "/Orders/ShoppingCart"
            };

            items.ForEach(item =>
            {
                var sessionLineItem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)(item.Movie.Price * 100),
                        Currency = "usd",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Movie.Name
                        }
                    },
                    Quantity = item.Amount
                };

                options.LineItems.Add(sessionLineItem);
            });

            var service = new SessionService();
            Session session = service.Create(options);

            Response.Headers.Add("Location", session.Url);

            return new StatusCodeResult(303);
        }

        public async Task<IActionResult> OrderConfirmation()
        {
            await shoppingCart.ClearShoppingCartAsync();
            return View("OrderCompleted");
        }
    }
}

eTickets/Controllers/ProducersController.cs
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;

namespace eTickets.Controllers
{
    public class ProducersController : Controller
    {
        private readonly IProducerService producerService;

        public ProducersController(IProducerService producerService)
        {
            this.producerService = producerService;
        }

        public async Task<IActionResult> Index()
        {
            var producers = await producerService.GetAllAsync();
            return View(producers);
        }

        public async Task<IActionResult> DetailsAsync(int id)
        {
            var producer = await producerService.GetByIdAsync(id);
            if (producer is null)
            {
                return View("NotFound");
            }

            return View(producer);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost, ActionName("Create")]
        public async Task<IActionResult> CreateAsync([Bind("ProfilePictureUrl", "FullName", "Bio")]Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }

            await producerService.AddAsync(producer);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> EditAsync(int id)
        {
            var producer = await producerService.GetByIdAsync(id);
            return producer is not null ? View(producer) : View("NotFound");
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(int id, Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }

            if (id == producer.Id)
            {
                await producerService.UpdateAsync(id, producer);
                return RedirectToAction(nameof(Index));
            }

            return View(producer);
        }

        public async Task<IActionResult> DeleteAsync(int id)
        {
            var producer = await producerService.GetByIdAsync(id);
            return producer is not null ? View(producer) : View("NotFound");
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmationAsync(int id)
        {
            var producer = await producerService.GetByIdAsync(id);
            if (producer is null)
            {
                return View("NotFound");
            }

            await producerService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTickets/Views/Movies/Create.cshtml
@model MovieViewModel
@{
    ViewData["title"] = "Create Movie";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new movie</h4>
        </p>

        <div class="row">
            <div class="col-md-8">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control"/>
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageUrl" class="control-label"></label>
                                <input asp-for="ImageUrl" class="form-control" />
                                <span asp-validation-for="ImageUrl" class="text-danger"></span>
                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="CinemaId" class="control-label"></label>
                                <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinemas"></select>
                                <span asp-validation-for="CinemaId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MovieCategoryId" class="control-label"></label>
                                <select asp-for="MovieCategoryId" class="form-control" asp-items="ViewBag.MovieCategories"></select>
                                <span asp-validation-for="MovieCategoryId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProducerId" class="control-label"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ActorIds" class="control-label"></label>
                                <select asp-for="ActorIds" class="form-control" asp-items="ViewBag.Actors"></select>
                                <span asp-validation-for="ActorIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control" rows="5"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right"/>
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
            <div class="col-md-4">
                <div class="text-center">
                    <img width="100%" id="MoviePosterPreview" />
                </div>
            </div>
        </div>
    </div>

</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial"></partial>

    <script>
        $(document).ready(function(){
            var output = document.getElementById("MoviePosterPreview");
            output.src = $("#ImageUrl").val();
        })

        $("#ImageUrl").on("change", function () {
            var output = document.getElementById("MoviePosterPreview");
            output.src = $(this).val();
        })
    </script>
}

eTickets/Views/Movies/Details.cshtml
@model Movie
@{
    ViewData["Title"] = "Movie Details";
}

<div class="row">
    <div class="col-md-8 offset-2">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageUrl" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Cinema: </b>
                        <a asp-controller="Cinemas" asp-action="Details" asp-route-id="@Model.CinemaId" class="text-decoration-none">@Model.Cinema.Name</a>
                        </p>
                        <p class="card-text">
                            <b>Producer: </b>
                        <a asp-controller="Producers" asp-action="Details" asp-route-id="@Model.ProducerId" class="text-decoration-none">@Model.Producer.FullName</a>
                        </p>
                        <p class="card-text"><b>Category: </b>@Model.MovieCategory.Name</p>
                        <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd MMMM yyyy")</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd MMMM yyyy")</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-capitalize">Available</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-capitalize">Expired</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-capitalize">Upcoming</span>
                            }
                        </p>
                        <p class="card-text">
                            <b>Actors</b>
                            <hr />
                            <div class="d-flex flex-row">
                                @foreach (var movieActor in Model.ActorMovies)
                                {
                                    <div class="column text-center">
                                        <img src="@movieActor.Actor.ProfilePictureUrl" class="border-info rounded-circle m-2" style="max-width: 150px;"/>
                                        <br />
                                    <a asp-controller="Actors" asp-action="Details" asp-route-id="@movieActor.ActorId" class="text-decoration-none">@movieActor.Actor.FullName</a>
                                    </div>
                                }
                            </div>
                        </p>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer ">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index"> Back to List</a>
                            <a class="btn btn-success text-white @((DateTime.Now > Model.EndDate) ? "disabled" : "")" asp-controller="Orders" asp-action="AddToCartFromHome" asp-route-id="@Model.Id"><i class="bi bi-cart-plus"></i> Add to Cart ($@Model.Price)</a>
                        </p>
                    </div>
                </div>
            </div>        
    </div>

</div>

eTickets/Views/Movies/Index.cshtml
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "Movies";
}

<div class="row">
    @foreach (Movie movie in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @movie.Name
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@movie.Id"><i class="bi bi-pencil-square"></i></a>
                                    }                                    
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@movie.ImageUrl" width="100%" alt="@movie.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">
                                @if (movie.Description.Length > 50)
                                {
                                    @movie.Description.Substring(0, 50)<span>...</span>
                                }
                                else
                                {
                                    @movie.Description
                                }
                            </p>
                            <p class="card-text"><b>Cinema: </b>@movie.Cinema.Name</p>
                            <p class="card-text"><b>Category: </b>@movie.MovieCategory.Name</p>
                            <p class="card-text"><b>Start Date: </b>@movie.StartDate.ToString("dd MMMM yyyy")</p>
                            <p class="card-text"><b>End Date: </b>@movie.EndDate.ToString("dd MMMM yyyy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= movie.StartDate && DateTime.Now <= movie.EndDate)
                                {
                                    <span class="badge bg-success text-capitalize">Available</span>
                                }
                                else if (DateTime.Now > movie.EndDate)
                                {
                                    <span class="badge bg-danger text-capitalize">Expired</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-capitalize">Upcoming</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@movie.Id"><i class="bi bi-eye-fill"></i> Show Details</a>
                                <a class="btn btn-success text-white @((DateTime.Now > movie.EndDate) ? "disabled" : "")" asp-controller="Orders" asp-action="AddToCartFromHome" asp-route-id="@movie.Id"><i class="bi bi-cart-plus"></i> Add to Cart ($@movie.Price)</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@await Html.PartialAsync("_CreateNewItem", "Movies")